import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import React, { useState } from 'react'
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import TemporaryDrawer from './Navbar'
import { Button } from '@mui/material'
import Socialmedia from './blogpost/Socialmedia'
import Firstyear from './cards/Firstyear'
import Footer from './cards/Footer'





  
  


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [state, setState] = useState(0);

  const increment = () => {
    setState(state + 1);
  }


  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='/sc.js'></script> */}
        {/* we need this script to lazy load */}
      </Head>
      <Script src='/sc.js'>

      </Script>
      <main className={styles.main}>
        
        <div className={styles.menu}>
        <div className={styles.thirteen}>
        <div className={styles.logo}>
            <img src='thirteen.svg' alt='Logo'></img>
          </div>
          </div>
          <TemporaryDrawer/>
          <TextField id="outlined-basic"  variant="outlined" style={{backgroundColor:'white', marginRight:'20px',borderRadius:'10px'}} placeholder="Search for anything..."/>
      <Button color="secondary" variant="contained">Search</Button>
      <Socialmedia/>
      </div>
      <div className={styles.frontLine}>
        <img src='Image1.avif' className={styles.image1} alt='Image'></img>
        <h1>Find the best course, Select the year from the menu below</h1>
      </div>

      <div className={styles.aboutDiploma}>
        <p id='text'>
        Diploma in engineering is one of the most sought-after courses. The course generally involves theoretical and practical classes on fundamental engineering concepts. After you pass your 10th standard, you can take admission to engineering diploma courses in various streams.Most engineering diploma courses run on semester or yearly basis for duration of total three years. Many other diplomas that follow a semester pattern may have a planned duration of total four years that involve three years of general study and one year of industrial internship. So, students enrolling to diploma courses after their class 10, do not necessarily have to waste extra years in study.Diploma in engineering makes students job-ready faster, so their chances of being hired and valued increase.As diploma courses are practical in nature, the amount of time students spend learning and completing assignments is greatly lessened, allowing them to enter the workforce and reap the benefits.
        </p>
      </div>

      {/* starting the course section */}
     <div className={styles.coursecards}>
     <Firstyear image={"Firstyear.png"} year={"FirstYear"} title={"First year is the combination of all branches where students gain excellence in the Applied Sccience field and make themselves comfortable for the engineering"} />
     <Firstyear image={"Secondyear.jpeg"} year={"SecondYear"} title={"From Second year, branchwise specialized education is provided to students so that they can get a basic knowledge of their respective branches and perform experiments in the lab"}/>
     <Firstyear image={"thirdyear.jpg"} year={"Third year"} title={"In third year which is the final year, branchwise projects are given and most importantly lab experiments are performed more vigilantly and carefully. Students have to make minor and major projects."}/>

     </div>

     <Footer/>





        {/* suppose if i want to use some javscript here */}
        {/* <div>
  <p>The value of the counter now is {state}</p>
       
          </div>
  <button onClick={increment}>Click me</button>
  
 </div> */}

      </main>
    </>
  )
}
